name: tests

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
jobs:
  test:
    name: test
    env:
      GOFLAGS: ""
      GOPROXY: ""
    strategy:
      matrix:
        goversion: [1.16.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}

      - name: Install protoc
        uses: arduino/setup-protoc@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile proto
        run: |
          go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
          go get -u google.golang.org/grpc
          make proto

      - name: Format
        run: make fmt

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          make lint

      - name: Vet
        run: make vet

      - name: Test
        run: |
          go install github.com/golang/mock/mockgen@v1.5.0
          make test

      - name: Build
        run: make build

      - name: Run
        run: |
          ./bin/registry serve &
          printf "123456\nan address\n2020-01-01\n" > test-data.txt
          cat test-data.txt | ./bin/registry client -r create KFG-734
          ./bin/registry client -r retrieve KFG-734
          ./bin/registry client -r delete KFG-734
